name: ci

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      # - run: pip install mkdocs-roamlinks-plugin # Pour convertir les [[liens internes]] en []()
      # - run: pip install mkdocs-git-revision-date-localized-plugin # Pour afficher la date de révision - https://pypi.org/project/mkdocs-git-revision-date-localized-plugin/
      # - run: pip install mkdocs-callouts 
      # - run: pip install mdx_breakless_lists
      # - run: pip install mkdocs-mermaid2-plugin 
      # - run: pip install mkdocs-exclude
      
      # - run: pip install mkdocs-jupyter 
      
      # C'est ici qu'il faut ajouter si besoin
      # les instructions pour installer avec pip
      # les autres plugins MkDocs ou extensions MarkDown
      # souhaités pour le déploiement du site...
      - run: mkdocs gh-deploy --force
      # --config-file Documentation/mkdocs.yml
